const videosActions = {
  SET_VIDEOS: "SET_VIDEOS",
  INITIALIZE: "INITIALIZE",
  SET_ERROR: "SET_ERROR",
  SET_CATEGORY: "SET_CATEGORY",
  APPLY_SEARCH_TERM: "APPLY_SEARCH_TERM",
  FILTER_BY_SEARCH:"FILTER_BY_SEARCH",
  SET_LIKES:"SET_LIKES",
  // ADD_LIKE_VIDEOS:"ADD_LIKE_VIDEOS",
  // REMOVE_LIKE_VIDEOS:"REMOVE_LIKE_VIDEOS",
  Default:"Default",
  Latest:"Latest",
  Earliest:"Earliest"
};

export { videosActions };
