export const UPDATE_LIKE_VIDEOS="UPDATE_LIKE_VIDEOS";
export const REMOVE_LIKE_VIDEOS='REMOVE_LIKE_VIDEOS'
export const UPDATE_WATCH_LATER_VIDEOS="UPDATE_WATCH_LATER_VIDEOS"
export const REMOVE_WATCH_LATER_VIDEOS="REMOVE_WATCH_LATER_VIDEOS"
export const ADD_TO_HISTORY="ADD_TO_HISTORY"
export const REMOVE_FROM_HISTORY="REMOVE_FROM_HISTORY"
export const CLEAR_ALL_HISTORY="CLEAR_ALL_HISTORY"